/*
Option 6
[Task 2 - quick sort wih recursion]

Debug the correct operation of sorts on arrays with
the number of elements N=50 generated by a random number generator in the range [16060, 36706]
*/

#include <cstdlib>
#include <ctime>
#include <iostream>

using namespace std;

void create_rnd_arr(short int arr[], int min_ch, int max_ch, int n);
void output_arr(short int arr[], int n);
void swap(int& a, int& b);

void quick_sort(short int arr[], int start, int n);
int dop_quick_sort(short int arr[], int start, int end);

int main() {
    time_t t;
    srand(time(&t));

    int min_ch = 16060;
    int max_ch = 36706;

    cout << "\n[Task 2 (quick sort with recursion)]" << endl;

    int n = 50;

    short int arr[n];

    create_rnd_arr(arr, min_ch, max_ch, n);
    cout << "\nArray for quick sort: \n";
    output_arr(arr, n);

    quick_sort(arr, 0, n - 1);

    cout << "\nSorted array by quick sort:\n";
    output_arr(arr, n);
}

void create_rnd_arr(short int arr[], int min_ch, int max_ch, int n) {
    for (int i = 0; i <= n; i++) {
        // num = m + rand() % (n - m + 1);
        arr[i] = rand() % (max_ch - min_ch + 1) + min_ch;
        if (arr[i] < 0) {
            arr[i] *= -1;
        }
    }
}

void output_arr(short int arr[], int n) {
    for (int i = 0; i < n; i++) cout << arr[i] << "  ";
    cout << "\n";
}

void quick_sort(short int arr[], int start, int end) {
    if (start >= end) {
        return;
    }

    int index_opora = dop_quick_sort(arr, start, end);

    quick_sort(arr, start, index_opora - 1);
    quick_sort(arr, index_opora + 1, end);
}

int dop_quick_sort(short int arr[], int start, int end) {
    int opora = arr[end];
    int index_sort = start;
    short int temp;

    for (int i = start; i < end; i++) {
        if (arr[i] <= opora) {
            swap(arr[i], arr[index_sort]);
            index_sort++;
        }
    }
    swap(arr[end], arr[index_sort]);

    return index_sort;
}

void swap(int& a, int& b) {
    int temp = a;
    a = b;
    b = temp;
}