/*
Option 6
[Task 2 - quick sort wihout recursion]

Debug the correct operation of sorts on arrays with
the number of elements N=50 generated by a random number generator in the range [16060, 36706]
*/

#include <time.h>

#include <cstdlib>
#include <iostream>
using namespace std;

void create_rnd_arr(short int arr[], int min_ch, int max_ch, int n);
void output_arr(short int arr[], int n);

void swap(int& a, int& b);
int rarefaction(short int arr[], int low, int high);
void quick_sort(short int arr[], int low, int high);

int main() {
    time_t t;
    srand(time(&t));

    int min_ch = 16060;
    int max_ch = 36706;

    cout << "\n[Task 2 (quick sort without recursion)]" << endl;
    int n = 50;
    short int arr[n];

    create_rnd_arr(arr, min_ch, max_ch, n);
    cout << "\nArray for quick sort: \n";
    output_arr(arr, n);

    quick_sort(arr, 0, n - 1);

    cout << "\nSorted array by quick sort:\n";
    output_arr(arr, n);
}

void create_rnd_arr(short int arr[], int min_ch, int max_ch, int n) {
    for (int i = 0; i <= n; i++) {
        // num = m + rand() % (n - m + 1);
        arr[i] = rand() % (max_ch - min_ch + 1) + min_ch;
        if (arr[i] < 0) {
            arr[i] *= -1;
        }
    }
}

void output_arr(short int arr[], int n) {
    for (int i = 0; i < n; i++) cout << arr[i] << "  ";
    cout << "\n";
}

void swap(int& a, int& b) {
    int temp = a;
    a = b;
    b = temp;
}

int rarefaction(short int arr[], int low, int high) {
    int opora = arr[high];
    int i = (low - 1);

    for (int j = low; j <= high - 1; j++) {
        if (arr[j] < opora) {
            i++;
            swap(arr[i], arr[j]);
        }
    }
    swap(arr[i + 1], arr[high]);
    return (i + 1);
}

void quick_sort(short int arr[], int low, int high) {
    int stack[high - low + 1];
    int top = -1;

    stack[++top] = low;
    stack[++top] = high;

    while (top >= 0) {
        high = stack[top--];
        low = stack[top--];

        int opora_index = rarefaction(arr, low, high);

        if (opora_index - 1 > low) {
            stack[++top] = low;
            stack[++top] = opora_index - 1;
        }

        if (opora_index + 1 < high) {
            stack[++top] = opora_index + 1;
            stack[++top] = high;
        }
    }
}